export { default as ErrorPage } from "./ErrorPage.svelte"

export { default as StayInside } from "./StayInside.svelte"
export { default as StayInsideDetail } from "./StayInsideDetail.svelte"
export { default as ColorAndShape } from "./ColorAndShape.svelte"
export { default as ColorAndShapeDetail } from "./ColorAndShapeDetail.svelte"
export { default as Tobi2Go } from "./Tobi2Go.svelte"
export { default as Tobi2GoDetail } from "./Tobi2GoDetail.svelte"
export { default as FixedGearCalc } from "./FixedGearCalc.svelte"
export { default as FixedGearCalcDetail } from "./FixedGearCalcDetail.svelte"